In [3]:
first_name = 'shruti'
last_name = 'paul'

In [5]:
print("my first name is {} and last name is {}" . format(first_name , last_name))

my first name is shruti and last name is paul


In [6]:
print("my first name is {first} and last name is {last}" . format(first = first_name ,last = last_name))

my first name is shruti and last name is paul


In [8]:
set_var = set()

In [9]:
print(set_var)


set()


In [14]:
set_var={"Avengers","IronMan","Hitman"}


In [15]:
set_var

{'Avengers', 'Hitman', 'IronMan'}

In [16]:
set_var.add('hulk')

In [17]:
set_var

{'Avengers', 'Hitman', 'IronMan', 'hulk'}

In [18]:
set1 = {"Avengers","IronMan",'Hitman'}
set2 = {'Avengers', 'Hitman', 'IronMan', 'hulk'}

In [19]:
set2.intersection_update(set1)

In [20]:
set2

{'Avengers', 'Hitman', 'IronMan'}

In [26]:
set1.difference(set2)
set1

{'Avengers', 'Hitman', 'IronMan'}

In [28]:
import numpy as np

In [39]:
my_lst1=[1,2,3,4,5]
my_lst2=[5,6,7,8,9]
my_lst3=[10,11,12,13,14]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
arr[1:,3:]

array([[ 8,  9],
       [13, 14]])

In [52]:
arr[1,1:4]

array([6, 7, 8])

In [55]:
arr[1:,3:]

array([[ 8,  9],
       [13, 14]])

In [62]:
arr=np.arange(0,21) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [66]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [85]:
#copy index and braodcasting
arr[3:] = 100

In [86]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [90]:
#conditions useful in exploratory data analysis 
val=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [91]:
val=2
arr[arr<2]

array([0, 1])

In [94]:
arr1 = np.arange(0,10).reshape(5,2)


In [97]:
arr2 = np.arange(0,10).reshape(5,2)


In [98]:
arr1 * arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [105]:
np.zeros(4,dtype=int)  #np.ones


array([0, 0, 0, 0])

In [107]:
np.ones((4,6),dtype=int)  #np.ones


array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [111]:
np.random.rand(3,2)  ## random distribution

array([[0.27850668, 0.81956325],
       [0.86612183, 0.80522091],
       [0.1417677 , 0.97490712]])

In [112]:
np.random.randn(4,4) ##standard normal distribution

array([[ 0.08619192, -0.33133961, -1.39886662, -1.36528967],
       [ 0.54171462,  0.42639654, -0.11755253, -0.64201678],
       [ 0.97124404,  0.29014031, -0.52590475, -0.18688492],
       [ 0.02220906,  0.2156756 , -0.62705882, -0.45118004]])

In [115]:
np.random.randint(0,100,10).reshape(2,5)

array([[58, 44, 91, 13, 35],
       [48, 88, 54, 71, 61]])

In [117]:
np.random.random_sample((1,5))

array([[0.05139997, 0.69227405, 0.12547318, 0.10706365, 0.92802647]])

In [118]:
import pandas as pd

C:\Users\spaul\AppData\Local\Temp\ipykernel_6940\4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [119]:
!pip install pandas

In [130]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Coumn4"])


In [127]:
df.head()

Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [132]:
df.to_csv('Test1.csv')

In [133]:
type(df.loc['Row2'])

pandas.core.series.Series

In [134]:
df.loc['Row2']

Column1    4
Column2    5
Column3    6
Coumn4     7
Name: Row2, dtype: int32

In [135]:
df.loc[:,:]

Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [141]:
type(df.loc[:,:])

pandas.core.frame.DataFrame

In [142]:
df.iloc[2:,2:]

Column3  Coumn4
Row3       10      11
Row4       14      15
Row5       18      19

In [143]:
type(df.iloc[2:,2:])

pandas.core.frame.DataFrame

In [145]:
#convert dataframes into arrays
df.iloc[2:,2:].values

array([[10, 11],
       [14, 15],
       [18, 19]])

In [146]:
df.iloc[2:,2:].values.shape

(3, 2)

In [148]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Coumn4     0
dtype: int64

In [149]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [150]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])